// ============================================================
// DATA STORE
// ============================================================
let db = {
  product_categories: [
    { id: 1, name: "Candy" },
    { id: 2, name: "Drinks" },
    { id: 3, name: "Snacks" },
    { id: 4, name: "Condiments" },
    { id: 5, name: "Personal Care" },
    { id: 6, name: "Cigarettes" },
    { id: 7, name: "Others" },
  ],
  expense_categories: [
    { id: 1, name: "Kumpra" },
    { id: 2, name: "Tubig" },
    { id: 3, name: "Kuryente" },
    { id: 4, name: "Transportasyon" },
    { id: 5, name: "Mga Bayronon" },
    { id: 6, name: "Uban Pa" },
  ],
  payment_types: [
    { id: 1, name: "cash" },
    { id: 2, name: "credit" },
  ],
  products: [
    {
      id: 1,
      name: "Snow Bear",
      category: "Candy",
      stock_quantity: 200,
      image_url: "🍬",
      retail_price: 1.0,
      wholesale_price: 0.65,
      wholesale_min_qty: 100,
    },
    {
      id: 2,
      name: "Chippy",
      category: "Snacks",
      stock_quantity: 45,
      image_url: "🍟",
      retail_price: 7.0,
      wholesale_price: 5.0,
      wholesale_min_qty: 24,
    },
    {
      id: 3,
      name: "Coke 237ml",
      category: "Drinks",
      stock_quantity: 24,
      image_url: "🥤",
      retail_price: 20.0,
      wholesale_price: 15.0,
      wholesale_min_qty: 24,
    },
    {
      id: 4,
      name: "Milo Sachet",
      category: "Drinks",
      stock_quantity: 8,
      image_url: "☕",
      retail_price: 8.0,
      wholesale_price: 6.0,
      wholesale_min_qty: 50,
    },
    {
      id: 5,
      name: "Marlboro Red",
      category: "Cigarettes",
      stock_quantity: 3,
      image_url: "🚬",
      retail_price: 7.0,
      wholesale_price: 5.5,
      wholesale_min_qty: 100,
    },
    {
      id: 6,
      name: "Lucky Me Pansit",
      category: "Snacks",
      stock_quantity: 60,
      image_url: "🍜",
      retail_price: 12.0,
      wholesale_price: 9.0,
      wholesale_min_qty: 24,
    },
    {
      id: 7,
      name: "Surf Sachet",
      category: "Personal Care",
      stock_quantity: 80,
      image_url: "🧼",
      retail_price: 6.0,
      wholesale_price: 4.5,
      wholesale_min_qty: 36,
    },
    {
      id: 8,
      name: "Toyo (soy sauce)",
      category: "Condiments",
      stock_quantity: 30,
      image_url: "🍶",
      retail_price: 5.0,
      wholesale_price: 3.5,
      wholesale_min_qty: 20,
    },
    {
      id: 9,
      name: "Magic Sarap",
      category: "Condiments",
      stock_quantity: 120,
      image_url: "🧂",
      retail_price: 2.0,
      wholesale_price: 1.5,
      wholesale_min_qty: 50,
    },
    {
      id: 10,
      name: "Skyflakes",
      category: "Snacks",
      stock_quantity: 15,
      image_url: "🍘",
      retail_price: 5.0,
      wholesale_price: 3.5,
      wholesale_min_qty: 30,
    },
  ],
  pricing: [],
  bundles: [
    {
      id: 1,
      name: "5-pc Snow Bear Deal",
      type: "single",
      items: [{ product_id: 1, qty: 5 }],
      bundle_price: 4.0,
    },
    {
      id: 2,
      name: "Chippy 3-pack",
      type: "single",
      items: [{ product_id: 2, qty: 3 }],
      bundle_price: 18.0,
    },
    {
      id: 3,
      name: "Merienda Combo",
      type: "multi",
      items: [
        { product_id: 3, qty: 1 },
        { product_id: 2, qty: 1 },
        { product_id: 1, qty: 3 },
      ],
      bundle_price: 29.0,
    },
  ],
  sales: [],
  sale_items: [],
  stock_logs: [
    {
      id: 1,
      product_id: 1,
      change_qty: 200,
      reason: "restock",
      notes: "Opening stock",
      log_date: "2025-02-15",
      expiration_date: "2026-06-01",
    },
    {
      id: 2,
      product_id: 5,
      change_qty: -2,
      reason: "damaged",
      notes: "Basang basang",
      log_date: "2025-02-18",
      expiration_date: null,
    },
  ],
  customers: [
    {
      id: 1,
      first_name: "Maria",
      middle_name: "",
      last_name: "Santos",
      contact_number: "09171234567",
      municipality: "",
      barangay: "Brgy. San Jose",
      street: "",
      credit_limit: 1000,
    },
    {
      id: 2,
      first_name: "Jose",
      middle_name: "",
      last_name: "Reyes",
      contact_number: "09281234567",
      municipality: "",
      barangay: "Brgy. Poblacion",
      street: "",
      credit_limit: 500,
    },
    {
      id: 3,
      first_name: "Ana",
      middle_name: "",
      last_name: "Cruz",
      contact_number: "09391234567",
      municipality: "",
      barangay: "Brgy. Santa Cruz",
      street: "",
      credit_limit: 1500,
    },
  ],
  credits: [
    {
      id: 1,
      customer_id: 1,
      sale_id: null,
      amount_owed: 85.0,
      amount_paid: 20,
      status: "partial",
      due_date: "2025-03-15",
      created_date: "2025-02-10",
    },
    {
      id: 2,
      customer_id: 2,
      sale_id: null,
      amount_owed: 150.0,
      amount_paid: 0,
      status: "unpaid",
      due_date: "2025-03-01",
      created_date: "2025-02-05",
    },
  ],
  expenses: [
    {
      id: 1,
      expense_category_id: 1,
      amount: 500.0,
      notes: "Nabili na produkto sa supplier",
      expense_date: "2025-02-15",
    },
    {
      id: 2,
      expense_category_id: 3,
      amount: 220.0,
      notes: "Bayad sa kuryente",
      expense_date: "2025-02-01",
    },
    {
      id: 3,
      expense_category_id: 2,
      amount: 50.0,
      notes: "Tubig ngayong buwan",
      expense_date: "2025-02-01",
    },
  ],
  nextId: {
    products: 11,
    customers: 4,
    sales: 1,
    sale_items: 1,
    credits: 3,
    expenses: 4,
    stock_logs: 3,
    bundles: 4,
  },
};

// ============================================================
// APP STATE
// ============================================================
let cart = [];
let cartBundles = []; // { bundle_id, quantity }
let payType = "cash";
let editingProductId = null;
let editingBundleId = null;
let payingCreditId = null;
let posMode = "products"; // 'products' | 'bundles'
let bundleSelectedItems = {}; // { product_id: qty } for multi bundle modal
let posCategory = "All";
let posSearch = "";
